[build-system]
requires = ["setuptools", "wheel", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "nearl"  # as it would appear on PyPI
version = "0.0.3.dev0"
description = "Nearl: A generalizable framework for 3D dynamic feature extraction"
authors = [
    {name = "Yang Zhang", email = "yangz3@kth.se"},
]
# Core dependencies
# NOTE: PyTraj 3.0.X.X should be installed separately
dependencies = [
    "numpy",
    "h5py",
    "scipy",
    "torch",
    "rdkit",
    "openbabel",
    "pybind11",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[project.urls]
Publication = "https://doi.org/10.1093/bioinformatics/btaf321"
Repository = "https://github.com/miemiemmmm/Nearl"
Documentation = "https://nearl.readthedocs.io/"

[tool.setuptools]
include-package-data = true

[tool.ruff]
target-version = "py39"
line-length = 88

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "B",
    "UP",
    "SIM",
    "RUF",
]
ignore = [
    "E501",  # line too long
    "B005",  # false-positives strip method
    "B008",  # function call in default argument
    "RUF022",  # unsorted list
    "E402",  # import not at the top
    "BLE001",  # unclear exception type
    "F401",  # unused import
    "F403",  # import with star
]

[project.entry-points.console_scripts]
nearl-view-slice = "nearl.visual:CLI_view_slice"
nearl-view-voxel = "nearl.visual:CLI_view_voxel"
