name: nearl_env

channels:
  - conda-forge
  - anaconda
  - pytorch
  - nvidia

dependencies:
  - python=3.9                # Tested with Python 3.9
  - ambertools                # For PyTraj support
  - numpy<2.0.0               # Numpy>2.0 breaks some dependencies 
  - openbabel
  - h5py
  - scipy
  - pytorch                   # Pytorch support
  - pytorch-cuda=12.4         # NOTE: Modify according to your CUDA device  
  # Other packages 
  - pip>=20.1
  - pip:
    - rdkit
    - tensorboard
    - pytest
    - pytest-benchmark 
    - open3d

# Other packages 
# pandas==2.0.3
# scikit-learn==1.3.0
# matplotlib==3.7.2
# seaborn
# notebook==6.5.4
# nglview==3.0.3
# line_profiler==4.0.3
